apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes2
  labels:
    app: notes2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes2
  template:
    metadata:
      labels:
        app: notes2
    spec:
      containers:
        - name: notes2-challenge
          image: docker.io/cookie303/notes:latest
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 1024
              protocol: TCP
              name: notes2-port
          resources:
            requests:
              cpu: 100m
