apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: useme
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: useme
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
