apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: got2win
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: got2win
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
