apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  labels:
    app: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
        - name: canary-challenge
          image: docker.io/cookie303/canary:latest
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 1024
              protocol: TCP
              name: canary-port
          resources:
            requests:
              cpu: 100m
