apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-microk8s
          ports:
            - name: catchme-port # challenge_name-port
              containerPort: 8888
              hostPort: 8888
              protocol: TCP
