apiVersion: apps/v1
kind: Deployment
metadata:
  name: catchme
  labels:
    app: catchme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catchme
  template:
    metadata:
      labels:
        app: catchme
    spec:
      containers:
        - name: catchme-challenge
          image: docker.io/cookie303/catchme:latest
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 1024
              protocol: TCP
              name: catchme-port
          resources:
            requests:
              cpu: 100m
