apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: catchme
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catchme
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
