apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notes
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notes
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
