apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-microk8s
          ports:
            - name: got2win-port # challenge_name-port
              containerPort: 5555
              hostPort: 5555
              protocol: TCP
