apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: $name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $name
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
