apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: canary
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
