apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pb
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
