apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hippy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hippy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
