apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-microk8s
          ports:
            - name: notes-port # challenge_name-port
              containerPort: 7777
              hostPort: 7777
              protocol: TCP
