version: '3.8'

services:
  app:
    image: patchme
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2048:2048" # Exposing port 1024
    user: "1000:1000" # Setting the UID and GID of the user inside the container
    ##stdin_open: true # Keeping STDIN open even if not attached
    #tty: true # Allocating a pseudo-TTY
